	  ! MODULE COMMONPARAM
	  ! IMPLICIT NONE
	  ! DOUBLE PRECISION CRITELEM
	  ! DIMENSION DDOTARR(37524,29)
	  ! SAVE
	  ! END MODULE


      SUBROUTINE UEXTERNALDB(LOP,LRESTART,TIME,DTIME,KSTEP,KINC)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION TIME(2)

      ! USER DEFINTION
	  REAL*8 DDOTARR(37524)
	  INTEGER PCYC, ISJUMP
	  COMMON /STATEINFO/ DDOTARR, PCYC, ISQUPDT
	  
	  IF (LOP.EQ.1) THEN
	    IF ((TIME(1)-PCYC).EQ.1) THEN
		  PCYC = PCYC+1
		  ISJUMP = 1
		ELSE
		  ISJUMP = 0
		ENDIF
	  ENDIF
	  
	  IF (LOP.EQ.2) THEN
	    
	  ENDIF
	  
      RETURN
      END	
	  
	  
      SUBROUTINE UMAT(STRESS, STATEV, DDSDDE, SSE, SPD, SCD,
     1 RPL, DDSDDT, DRPLDE, DRPLDT,
     2 STRAN, DSTRAN, TIME, DTIME, TEMP, DTEMP, PREDEF, DPRED, CMNAME,
     3 NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS, COORDS, DROT, PNEWDT,
     4 CELENT, DFGRD0, DFGRD1, NOEL, NPT, LAYER, KSPT, JSTEP, KINC)
	  !USE COMMONPARAM !USER MODULE
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS), STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS), DDSDDT(NTENS), DRPLDE(NTENS),
     2 STRAN(NTENS), DSTRAN(NTENS), TIME(2), PREDEF(1), DPRED(1),
     3 PROPS(NPROPS), COORDS(3), DROT(3,3), DFGRD0(3,3), DFGRD1(3,3),
     4 JSTEP(4)

      ! USER DEFINITION
      DOUBLE PRECISION E, NU, SU, SL0, BETA, M0, B1, B2, A, TOL, 
     1 FACTOR1, FACTOR2, FACTOR3, DMG, NCYC, SH_MAX, SH_MIN, SEQ_MAX, 
     2 NF, I1, I2, J2, SEQ, SH, SH_MEAN, DEV_AMP, AII, AII_STAR, 
     3 MACAULAY, ALPHA, DDOT, DN, DDMG
      DIMENSION DEV_MAX(NTENS), DEV_MIN(NTENS), DEV(NTENS)
	  
	  REAL*8 DDOTARR(37524)
	  INTEGER PCYC, ISJUMP
	  COMMON /STATEINFO/ DDOTARR, PCYC, ISQUPDT

      E = PROPS(1)
      NU = PROPS(2)
      SU = PROPS(3)
      SL0 = PROPS(4)
      BETA = PROPS(5)
      M0 = PROPS(6)
      B1 = PROPS(7)
      B2 = PROPS(8)
      A = PROPS(9)
      TOL = PROPS(10)
      NF = 1.0D5

      DMG = STATEV(1)
	  NCYC = STATEV(2)
	  SEQ_MAX = STATEV(3)
      SH_MAX = STATEV(4)
      SH_MIN = STATEV(5)
      DO I = 1, NTENS
        DEV_MAX(I) = STATEV(I+5)
        DEV_MIN(I) = STATEV(I+11)
      ENDDO

	  IF (ISJUMP.EQ.1)) THEN
		IF (DDOT .LE. 1.0D-4) THEN
		  DN = 0.08*NF
		ELSE IF ((DDOT .GT. 1.0D-4) .AND. (DDOT .LE. 1.0D-2)) THEN
		  DN = 0.04*NF
		ELSE
		  DN = 0.01*NF
		ENDIF
		DDMG = DDOT*DN
		IF ((DMG+DDMG) .LE. 1) THEN
		  DMG = DMG+DDMG
		  NCYC = NCYC+DN
		ENDIF
      ENDIF

      FACTOR1 = E*(1-DMG)/(1+NU)/(1-2*NU)
      FACTOR2 = (1-NU)
      FACTOR3 = (1-2*NU)/2

      DO I = 1, NTENS
	    DO J = 1,NTENS
	      DDSDDE(I,J) = 0
	    ENDDO
      ENDDO

      DDSDDE(1,1) = (FACTOR1*FACTOR2)
      DDSDDE(2,2) = (FACTOR1*FACTOR2)
      DDSDDE(3,3) = (FACTOR1*FACTOR2)
      DDSDDE(4,4) = (FACTOR1*FACTOR3)
      DDSDDE(5,5) = (FACTOR1*FACTOR3)
      DDSDDE(6,6) = (FACTOR1*FACTOR3)
      DDSDDE(1,2) = (FACTOR1*NU)
      DDSDDE(1,3) = (FACTOR1*NU)
      DDSDDE(2,3) = (FACTOR1*NU)
      DDSDDE(2,1) = (FACTOR1*NU)
      DDSDDE(3,1) = (FACTOR1*NU)
      DDSDDE(3,2) = (FACTOR1*NU)

      DO I = 1, NTENS
	   DO J = 1,NTENS
	      STRESS(I) = STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
	   ENDDO
      ENDDO

      I1 = STRESS(1)+STRESS(2)+STRESS(3)
      I2 = STRESS(1)*STRESS(2)+STRESS(2)*STRESS(3)+STRESS(3)*STRESS(1)
     1 -STRESS(4)**2-STRESS(5)**2-STRESS(6)**2
      J2 = I2-I1**2/3
	  
	  SEQ = (-3*J2)**0.5
      IF (SEQ .GT. SEQ_MAX) THEN
		SEQ_MAX = SEQ
      ENDIF

      SH = I1/3
      IF(SH .GT. SH_MAX) THEN
        SH_MAX = SH
      ELSE IF (SH .LT. SH_MIN) THEN
        SH_MIN = SH
      END IF
      
      DO I = 1, NTENS
		IF(I .LE. 3) THEN
		  DEV(I) = STRESS(I)-SH
		ELSE
		  DEV(I) = STRESS(I)
		ENDIF
		IF (DEV(I) .GT. DEV_MAX(I)) THEN
		  DEV_MAX(I) = DEV(I)
		ELSE IF (DEV(I) .LT. DEV_MIN(I)) THEN
		  DEV_MIN(I) = DEV(I)
		ENDIF
      ENDDO
	  
	  IF ((TIME(1)+DTIME-PCYC).EQ.1) THEN
		SH_MEAN = (SH_MAX+SH_MIN)/2
		DEV_AMP = 0
		DO I = 1, NTENS
		  DEV_AMP = DEV_AMP+(DEV_MAX(I)-DEV_MIN(I))**2
		ENDDO
		AII = (3/2*DEV_AMP)**0.5/2
		AII_STAR = SL0*(1-3*B1*SH_MEAN)
		ALPHA = 1-A*MACAULAY((AII-AII_STAR)/(SU-SEQ_MAX))
		DDOT = (1-(1-DMG)**(1+BETA))**ALPHA*
     1  (AII/(M0*(1-3*B2*SH_MEAN)*(1-DMG)))**BETA
!             IF (NCYC .EQ. 0) THEN
!                   NF = MACAULAY((SU-SEQ_MAX)/(AII-AII_STAR))/
!      1            (1+BETA)/A*(M0*(1-3*B2*SH_MEAN)/AII)**BETA
!             ENDIF
		DDOTARR(NOEL) = DDOT
	  ENDIF

      STATEV(1) = DMG
	  STATEV(2) = NCYC
	  STATEV(3) = SEQ_MAX
      STATEV(4) = SH_MAX
      STATEV(5) = SH_MIN
      DO I = 1, NTENS
		STATEV(I+5) = DEV_MAX(I)
		STATEV(I+11) = DEV_MIN(I)
      ENDDO

      RETURN
      END


      SUBROUTINE SDVINI(STATEV, COORDS, NSTATV, NCRDS, NOEL, NPT, 
     1 LAYER, KSPT)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION STATEV(NSTATV), COORDS(NCRDS)
      ! USER DEFINITION
      STATEV(1) = 1.0D-5
      RETURN
      END


      DOUBLE PRECISION FUNCTION MACAULAY(ARG)
      DOUBLE PRECISION ARG
      MACAULAY = (ARG+DABS(ARG))/2
      RETURN
      END

