      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4)

C USER SUBROUTINE STARTS ==>> FOR ELASTIC ISOTROPIC MATERIAL
      DOUBLE PRECISION ZERO, ONE, TWO, E, NU, LAMBDA_1, LAMBDA_2, LAMBDA_3
      PARAMETER (ZERO=0.0D0, ONE=1.0D0, TWO=2.0D0)

      CALL GETVRM('SDV',ARRAY,JARRAY,FLGRAY,JRCD,JMAC,JMATYP,MATLAYO,LACCFLA)
      DAMAGE_PARAM = ARRAY(1)

      E=PROPS(1)*(1-DAMAGE_PARAM)
      NU=PROPS(2)
      LAMBDA_1=E/(ONE+NU)/(ONE-TWO*NU)
      LAMBDA_2=(ONE-NU)
      LAMBDA_3=(ONE-TWO*NU)/TWO
      DO I=1,NTENS
	    DO J=1,NTENS
	    DDSDDE(I,J)=ZERO
	    ENDDO
      ENDDO
      DDSDDE(1,1)=(LAMBDA_1*LAMBDA_2)
      DDSDDE(2,2)=(LAMBDA_1*LAMBDA_2)
      DDSDDE(3,3)=(LAMBDA_1*LAMBDA_2)
      DDSDDE(4,4)=(LAMBDA_1*LAMBDA_3)
      DDSDDE(5,5)=(LAMBDA_1*LAMBDA_3)
      DDSDDE(6,6)=(LAMBDA_1*LAMBDA_3)
      DDSDDE(1,2)=(LAMBDA_1*NU)
      DDSDDE(1,3)=(LAMBDA_1*NU)
      DDSDDE(2,3)=(LAMBDA_1*NU)
      DDSDDE(2,1)=(LAMBDA_1*NU)
      DDSDDE(3,1)=(LAMBDA_1*NU)
      DDSDDE(3,2)=(LAMBDA_1*NU)
      DO I=1,NTENS
	   DO J=1,NTENS
	   STRESS(I)=STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
	   ENDDO
      ENDDO
      
      STATEV(1) = DAMAGE_PARAM
C USER SUBROUTINE ENDS

      RETURN
      END

